server:
  port: 8084

spring:
  application:
    name: post-report-service


  liquibase:
    change-log: 'classpath:/db/changelog/liquibase.change-log.xml'
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud: #https://cloud.spring.io/spring-cloud-stream-binder-rabbit/multi/multi__retry_with_the_rabbitmq_binder.html , https://docs.spring.io/spring-cloud-stream-binder-rabbit/docs/3.1.3/reference/html/spring-cloud-stream-binder-rabbit.html#_rabbitmq_consumer_properties
    stream:
      bindings:
        post-creation-events:
          binder: rabbit
          content-type: application/json
          destination: post-creation-events
          durable-subscription: true
          group: post-report-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.example.demo_resource_server: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.security: trace